title: 1ps0 | Digital Outpost
description: Exploring the digital frontier
url: https://1ps0.github.io
baseurl: ""

# Build settings
markdown: kramdown
permalink: /blog/:title/

collections:
  posts:
    output: true
    permalink: /blog/:title/

include: ['_pages']

# Don't process these files
exclude:
  - README.md
  - .gitignore

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
